import { IpLocationData, IpLocationApiResponse } from '@/interfaces/geo.types';

// IP 위치 정보 목데이터 (제공해주신 데이터 기반)
export const MOCK_IP_LOCATION_DATA: IpLocationData = {
  ip: '165.132.5.129',
  network: '165.132.0.0/19',
  version: 'IPv4',
  city: 'Guro-gu',
  region: 'Seoul',
  region_code: '11',
  country: 'KR',
  country_name: 'South Korea',
  country_code: 'KR',
  country_code_iso3: 'KOR',
  country_capital: 'Seoul',
  country_tld: '.kr',
  continent_code: 'AS',
  in_eu: false,
  postal: '08367',
  latitude: 37.4975,
  longitude: 126.8501,
  timezone: 'Asia/Seoul',
  utc_offset: '+0900',
  country_calling_code: '+82',
  currency: 'KRW',
  currency_name: 'Won',
  languages: 'ko-KR,en',
  country_area: 98480.0,
  country_population: 51635256,
  asn: 'AS3786',
  org: 'LG DACOM Corporation',
};

// API 응답 형태의 목데이터
export const MOCK_IP_LOCATION_API_RESPONSE: IpLocationApiResponse = {
  status: 200,
  message: '요청에 성공하였습니다.',
  data: MOCK_IP_LOCATION_DATA,
};

// 다른 지역 예시 데이터들
export const MOCK_IP_LOCATION_EXAMPLES: IpLocationData[] = [
  MOCK_IP_LOCATION_DATA, // 서울
  {
    ip: '8.8.8.8',
    network: '8.8.8.0/24',
    version: 'IPv4',
    city: 'Mountain View',
    region: 'California',
    region_code: 'CA',
    country: 'US',
    country_name: 'United States',
    country_code: 'US',
    country_code_iso3: 'USA',
    country_capital: 'Washington',
    country_tld: '.us',
    continent_code: 'NA',
    in_eu: false,
    postal: '94043',
    latitude: 37.386,
    longitude: -122.0838,
    timezone: 'America/Los_Angeles',
    utc_offset: '-0800',
    country_calling_code: '+1',
    currency: 'USD',
    currency_name: 'Dollar',
    languages: 'en-US,es-US,haw,fr',
    country_area: 9833517.0,
    country_population: 331002651,
    asn: 'AS15169',
    org: 'Google LLC',
  },
  {
    ip: '1.1.1.1',
    network: '1.1.1.0/24',
    version: 'IPv4',
    city: 'Tokyo',
    region: 'Tokyo',
    region_code: '13',
    country: 'JP',
    country_name: 'Japan',
    country_code: 'JP',
    country_code_iso3: 'JPN',
    country_capital: 'Tokyo',
    country_tld: '.jp',
    continent_code: 'AS',
    in_eu: false,
    postal: '100-0001',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    utc_offset: '+0900',
    country_calling_code: '+81',
    currency: 'JPY',
    currency_name: 'Yen',
    languages: 'ja',
    country_area: 377975.0,
    country_population: 125836021,
    asn: 'AS13335',
    org: 'Cloudflare, Inc.',
  },
];
